# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Covfefe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Stripe'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'

  # Pods for Covfefe

  target 'CovfefeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
